### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by mpejcinovska** [jwonc4602/Analyzing-Geographic-and-Demographic-Patterns-of-Homelessness#1]
At the moment, this submission seems incomplete.  Please familiarize yourself with the rubric and make sure that your final submission addresses all the major areas identified in it. You are on the right track — the abstract is generally well done, but need to add actual findings instead of focusing on goals of analysis.

**Comment by jwonc4602** [comment]
Hi! Thank you so much for your comment. I just finished the final revision, if you have any chance, can you leave any comment if there is something I am missing before I submit it? If you don't have enough time to look before the deadline, it is fine though. Thank you.
